name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Assurez-vous que le dépôt Git est configuré
          if [ ! -d "/home/adminlocal/projet-code-quality/.git" ]; then
            git clone https://github.com/Florence-Martin/projet-code-quality.git /home/adminlocal/projet-code-quality
          fi

          # Naviguez dans le répertoire du projet
          cd /home/adminlocal/projet-code-quality

          # Ajoutez les chemins pour npm et pm2 dans le PATH
          export PATH=$PATH:/usr/local/bin

          # Récupérez les dernières modifications du dépôt
          git pull origin main

          # Installez les dépendances
          npm install

          # Construisez l'application
          npm run build

          # Redémarrez ou démarrez l'application avec PM2
          pm2 restart projet-code-quality || pm2 start npm --name "projet-code-quality" -- start